# -*- coding: utf-8 -*-
"""Bollinger_Bands_PineScript_V1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IceUEoKtRZ17gX9RKWqZ6aa3Xc_b-9s2
"""

// This strategy uses Bollinger Bands to detect consolidating markets and breakouts,
// with configurable input parameters, re-entry rules, dynamic stop-loss and max-trades management.

// Input parameters
length = input(20, minval=1)
multiplier = input(2)
consolidationPeriod = input(5, minval=1)
consolidationThreshold = input(0.05, minval=0.001, maxval=0.1)
atrPeriod = input(14, minval=1)
atrMultiple = input(3)
maxTradesPerDay = input(5, minval=1)

// Define Bollinger Bands
upperBand = sma(close, length) + multiplier * stdev(close, length)
middleBand = sma(close, length)
lowerBand = sma(close, length) - multiplier * stdev(close, length)

// Detect consolidating markets
consolidation = abs(close - middleBand) < consolidationThreshold

// Exit any existing positions if we're in a consolidation period
if consolidation
    exit("Consolidation detected")

// Enter a long position if the price breaks above the upper Bollinger Band
if close > upperBand
    entry(strategy.long)

// Enter a short position if the price breaks below the lower Bollinger Band
if close < lowerBand
    entry(strategy.short)

// Re-enter the market if the price breaks out of the consolidation in the opposite direction
if timenow > timenow[1] and not consolidation and consolidation[1]
    if close > upperBand[1]
        entry(strategy.long)
    else if close < lowerBand[1]
        entry(strategy.short)

// Apply risk management
atr = avgTrueRange(atrPeriod)
stopLoss = atrMultiple * atr
strategy.stopLoss(stopLoss, "ATR-based stop-loss")
strategy.maxTrades(maxTradesPerDay)